/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminBrokersRouteImport } from './routes/admin.brokers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminCommissionRouteImport } from './routes/admin.commission'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminFeaturedRouteImport } from './routes/admin.featured'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRequirementsRouteImport } from './routes/admin.requirements'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVisitsRouteImport } from './routes/admin.visits'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as PostPropertyRouteImport } from './routes/post.property'
import { Route as PostRequirementRouteImport } from './routes/post.requirement'
import { Route as PostServiceRouteImport } from './routes/post.service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrokersRoute = AdminBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionRoute = AdminCommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturedRoute = AdminFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequirementsRoute = AdminRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitsRoute = AdminVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AdminRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPropertyRoute = PostPropertyRouteImport.update({
  id: '/post/property',
  path: '/post/property',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRequirementRoute = PostRequirementRouteImport.update({
  id: '/post/requirement',
  path: '/post/requirement',
  getParentRoute: () => rootRouteImport,
} as any)
const PostServiceRoute = PostServiceRouteImport.update({
  id: '/post/service',
  path: '/post/service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/requirements': typeof RequirementsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/student': typeof StudentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requirements': typeof AdminRequirementsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/listing/$id': typeof ListingIdRoute
  '/post/property': typeof PostPropertyRoute
  '/post/requirement': typeof PostRequirementRoute
  '/post/service': typeof PostServiceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/requirements': typeof RequirementsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/student': typeof StudentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requirements': typeof AdminRequirementsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/listing/$id': typeof ListingIdRoute
  '/post/property': typeof PostPropertyRoute
  '/post/requirement': typeof PostRequirementRoute
  '/post/service': typeof PostServiceRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/requirements': typeof RequirementsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/student': typeof StudentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requirements': typeof AdminRequirementsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/listing/$id': typeof ListingIdRoute
  '/post/property': typeof PostPropertyRoute
  '/post/requirement': typeof PostRequirementRoute
  '/post/service': typeof PostServiceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/requirements'
    | '/saved'
    | '/search'
    | '/services'
    | '/student'
    | '/admin/announcements'
    | '/admin/brokers'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/cities'
    | '/admin/commission'
    | '/admin/contacts'
    | '/admin/featured'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/offers'
    | '/admin/reports'
    | '/admin/requirements'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/visits'
    | '/listing/$id'
    | '/post/property'
    | '/post/requirement'
    | '/post/service'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/requirements'
    | '/saved'
    | '/search'
    | '/services'
    | '/student'
    | '/admin/announcements'
    | '/admin/brokers'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/cities'
    | '/admin/commission'
    | '/admin/contacts'
    | '/admin/featured'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/offers'
    | '/admin/reports'
    | '/admin/requirements'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/visits'
    | '/listing/$id'
    | '/post/property'
    | '/post/requirement'
    | '/post/service'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/requirements'
    | '/saved'
    | '/search'
    | '/services'
    | '/student'
    | '/admin/announcements'
    | '/admin/brokers'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/cities'
    | '/admin/commission'
    | '/admin/contacts'
    | '/admin/featured'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/offers'
    | '/admin/reports'
    | '/admin/requirements'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/visits'
    | '/listing/$id'
    | '/post/property'
    | '/post/requirement'
    | '/post/service'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  RequirementsRoute: typeof RequirementsRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  StudentRoute: typeof StudentRoute
  ListingIdRoute: typeof ListingIdRoute
  PostPropertyRoute: typeof PostPropertyRoute
  PostRequirementRoute: typeof PostRequirementRoute
  PostServiceRoute: typeof PostServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brokers': {
      id: '/admin/brokers'
      path: '/brokers'
      fullPath: '/admin/brokers'
      preLoaderRoute: typeof AdminBrokersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commission': {
      id: '/admin/commission'
      path: '/commission'
      fullPath: '/admin/commission'
      preLoaderRoute: typeof AdminCommissionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/featured': {
      id: '/admin/featured'
      path: '/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AdminFeaturedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requirements': {
      id: '/admin/requirements'
      path: '/requirements'
      fullPath: '/admin/requirements'
      preLoaderRoute: typeof AdminRequirementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visits': {
      id: '/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AdminVisitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/property': {
      id: '/post/property'
      path: '/post/property'
      fullPath: '/post/property'
      preLoaderRoute: typeof PostPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/requirement': {
      id: '/post/requirement'
      path: '/post/requirement'
      fullPath: '/post/requirement'
      preLoaderRoute: typeof PostRequirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/service': {
      id: '/post/service'
      path: '/post/service'
      fullPath: '/post/service'
      preLoaderRoute: typeof PostServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBrokersRoute: typeof AdminBrokersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminCommissionRoute: typeof AdminCommissionRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminFeaturedRoute: typeof AdminFeaturedRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRequirementsRoute: typeof AdminRequirementsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVisitsRoute: typeof AdminVisitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBrokersRoute: AdminBrokersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChatRoute: AdminChatRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminCommissionRoute: AdminCommissionRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminFeaturedRoute: AdminFeaturedRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRequirementsRoute: AdminRequirementsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVisitsRoute: AdminVisitsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  RequirementsRoute: RequirementsRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  StudentRoute: StudentRoute,
  ListingIdRoute: ListingIdRoute,
  PostPropertyRoute: PostPropertyRoute,
  PostRequirementRoute: PostRequirementRoute,
  PostServiceRoute: PostServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
